#!/usr/bin/env python
#
# Merge the output files produced by smips_download.py into a single file for
# each variable, by combining the site-level CSV files into a single file with
# a site column.
#

import glob, os, pandas, sys

def main(out_dir: str):
    for subdir in os.listdir(out_dir):
        if not os.path.isdir(os.path.join(out_dir, subdir)):
            continue

        var = os.path.basename(subdir)

        var_dir = os.path.join(out_dir, subdir)

        dfs = []
        for file in glob.glob(os.path.join(var_dir, "*.csv")):
            site = os.path.basename(file)
            # Remove file extension
            site = os.path.splitext(site)[0]
            df = pandas.read_csv(file)
            # Add site column
            df["site"] = site
            dfs.append(df)

        # Concatenate all dataframes (which should have the same columns)
        df = pandas.concat(dfs)
        # Order by site then date.
        df = df.sort_values(["site", "date"])
        # Write to compressed CSV file.
        out_file = os.path.join(out_dir, f"{var}.csv.gz")
        df.to_csv(out_file, index = False, compression="gzip")

if __name__ == "__main__":
    if len(sys.argv) != 2 or not os.path.isdir(sys.argv[1]):
        print("Usage: merge_site_csv_files <out_dir>")
        sys.exit(1)
    out_dir = sys.argv[1]
    main(out_dir)
